# Test your FastAPI endpoints
####

POST http://127.0.0.1:8000/white/predict
Content-Type: application/json

{
  "alcohol": 14.4,
  "volatile_acidity": 0.28,
  "residual_sugar": 5.2,
  "free_sulfur_dioxide": 34,
  "density": 0.9937
}
###
